In [2]:
import numpy as np

In [3]:
#creating an array
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
#referencing the values in an array
my_array = np.array([1,2,3,4,5])

In [5]:
# just like a list

In [6]:
a = np.array([1, 2, 3])

In [7]:
a

array([1, 2, 3])

In [8]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
a[0]


1

In [10]:
print('a    == {}'.format(a))
print('a[0] == {}'.format(a[0]))
print('a[1] == {}'.format(a[1]))
print('a[2] == {}'.format(a[2]))


a    == [1 2 3]
a[0] == 1
a[1] == 2
a[2] == 3


In [11]:
matrix[1, 1]


5

In [14]:
matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
matrix[1:, :2]


array([[4, 5],
       [7, 8]])

In [15]:
matrix[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [20]:
my_array

array([1, 2, 3, 4, 5])

In [1]:
#Arrays can also be indexed with a boolean sequence used to indicate which values should be included in the 
#resulting array.
should_include_elements = [False, True, False, True, False]
a[should_include_elements]

NameError: name 'a' is not defined

In [21]:
mask = [False, True, False, True, False]

my_array[mask]

array([2, 4])

In [22]:
#Vectorized Operations
#Another useful feature of numpy arrays is vectorized operations.
#If we wanted to add 1 to every element in a list, without numpy, we can't simply add 1 to the list, 
#as that will result in a TypeError.

my_array


array([1, 2, 3, 4, 5])

In [23]:
my_array + 1

array([2, 3, 4, 5, 6])

In [24]:
my_array - 5

array([-4, -3, -2, -1,  0])

In [26]:
my_array // 2

array([0, 1, 1, 2, 2])

In [27]:
my_array % 2

array([1, 0, 1, 0, 1])

In [28]:
my_array > 2

array([False, False,  True,  True,  True])

In [29]:
my_array[my_array > 2]

array([3, 4, 5])

In [30]:
my_array % 2 == 0

array([False,  True, False,  True, False])

In [31]:
my_array[my_array % 2 == 0]

array([2, 4])

In [2]:

original_array = [1, 2, 3, 4, 5]
try:
    original_array + 1
except TypeError as e:
    print('An Error Occured!')
    print(f'TypeError: {e}')

An Error Occured!
TypeError: can only concatenate list (not "int") to list


In [19]:
original_array = [1, 2, 3, 4, 5]
array_with_one_added = []
for n in original_array:
    array_with_one_added.append(n + 1)
print(array_with_one_added)


[2, 3, 4, 5, 6]


In [33]:
np.random.randn(10)

array([ 1.36884937, -1.11174488,  2.57843546,  0.62338075,  1.29107679,
       -1.64511881, -0.00956232,  1.18205591, -0.17344969, -0.61186007])

In [34]:
np.random.randn(2,2)

array([[-0.4845394 , -0.9795268 ],
       [ 0.32915948, -0.03175213]])

In [47]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
np.full((5,5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [41]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [53]:
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [54]:
np.linspace(1,4,5)

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [55]:
a = np.array([1, 2, 3, 4, 5])


In [57]:
a.mean()

3.0

In [58]:
a.min()

1

In [60]:
a.max()

5

In [61]:
a.sum()

15

In [62]:
a.std()

1.4142135623730951

In [63]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
matrix.mean()

5.0